FROM node:16.20.0-alpine3.17 as builder

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./

RUN npm install && npm install axios

COPY . .

RUN npm run build

# multi-stage build
FROM nginx:stable-alpine

WORKDIR /usr/share/nginx/html

RUN rm -rf ./*

COPY --from=builder /app/build .

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]