version: "3.8"

services:
  db:
    image: "mongo"
    restart: always
    ports:
      - "27017:27017"
    
  backend: 
    # build: ./server
    image: stasyk003/go-react-api:back-end.v1.0
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    # build: ./client
    image: stasyk003/go-react-api:front-end.v1.0
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend

